
server:
  port: 8090

spring:
  application:
    name: management

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update        # update = crée les tables si elles n'existent pas, ajoute les colonnes manquantes sans supprimer les données
    open-in-view: false
    show-sql: true            # affiche les requêtes SQL dans la console
    properties:
      hibernate:
        format_sql: true



  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:192.168.178.27:9092}

    producer:
      acks: all
      retries: 3
      compression-type: snappy
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 1
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000
        # est pour chaque File dans Memory buffer de kafka
        linger.ms: 5
        batch.size: 16384
        # est un peu comme la liste d'attente ou queue pour les message qui n'ont pas pu etre envoyer a T= 0
        buffer.memory: 33554432

    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:stock-management-group}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      max-poll-records: 50 # veut dire « au maximum 50 messages par poll », pas « attends qu'il y en ait 50 avant de traiter ». Le consumer traite tout ce qui est disponible immédiatement, dans la limite de 50.
      properties:
        fetch.min.bytes: 50000 # si les 50000 octect sont atteint avant le fetch.max.wait.time le broker envoie le message au thread specifique
        fetch.max.wait.ms: 500 # meme si fetch.min.bytes n#est pas atteind et que fetch.max.wait.time est arriver le broker envoi les message au thread destinee
        max.poll.interval.ms: 300000 # ci apres ce temps passer le thread n'a pas encore fini kafka declenche un Rebalance et declare le thread comme defectueux
        session.timeout.ms: 30000
        heartbeat.interval.ms: 10000 # bip envoyer a kafka tte les 10seconde pour  lui dire que tout marche
        spring.json.trusted.packages: "com.stock.management.kafka.event"
        spring.json.use.type.headers: true

    listener:
      type: batch # 👈 INDISPENSABLE pour recevoir la List<ConsumerRecord>
      ack-mode: manual_immediate
      concurrency: 3
      poll-timeout: 3000
      missing-topics-fatal: false


  mail:
    host: smtp.gmail.com
    port: 587
    username: ktdtchofo@gmail.com
    password: wcjqgovpztthcwec
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
          # Spring Security contacte ce endpoint au démarrage pour récupérer la clé publique (JWKS)
          # et valider la signature de chaque token entrant.
          # Format : http://<keycloak-host>:<port>/realms/<votre-realm>
#          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://192.168.178.27:8090/realms/orderManagement}

#app:
#  security:
#    keycloak:
      # Doit correspondre exactement au Client ID configuré dans Keycloak
      # (utilisé pour extraire resource_access.{client-id}.roles)
#      client-id: ${KEYCLOAK_CLIENT_ID:order-management-app}
